name: Rustdoc

on:
  push:
    branches:
      - main

env:
  PROJECT_NAME: ${{ github.event.repository.name }}
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  rustdoc:
    name: Rustdoc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install `nightly` toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          components: rust-docs
          override: true

      - name: Restore cache
        uses: Swatinem/rust-cache@v2

      - name: Cargo Doc
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --all --release --no-deps --lib

      - name: Add index file
        run: |
          echo '<meta http-equiv="refresh" content="0; url='"$PROJECT_NAME"'">' > ./target/doc/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
